services:
  - type: web
    name: warehouse-app
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DIRECTUS_URL
        fromService:
          type: web
          name: directus
          property: host
        # Or use a static value if you have an external Directus instance
        # value: https://your-directus-instance.com
      - key: DIRECTUS_TOKEN
        # Set this in Render dashboard as a secret
        sync: false